# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_transfer_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61ta_transfer_api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n\x05Value\x12/\n\x0bupdate_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"3\n\x12StoreValueResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0fGetValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\")\n\x10GetValueResponse\x12\x15\n\x05value\x18\x01 \x01(\x0b\x32\x06.Value\"7\n\x11StoreValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value2}\n\x0fKeyValueService\x12\x31\n\x08GetValue\x12\x10.GetValueRequest\x1a\x11.GetValueResponse\"\x00\x12\x37\n\nStoreValue\x12\x12.StoreValueRequest\x1a\x13.StoreValueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_transfer_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VALUE']._serialized_start=60
  _globals['_VALUE']._serialized_end=133
  _globals['_STOREVALUERESPONSE']._serialized_start=135
  _globals['_STOREVALUERESPONSE']._serialized_end=186
  _globals['_GETVALUEREQUEST']._serialized_start=188
  _globals['_GETVALUEREQUEST']._serialized_end=218
  _globals['_GETVALUERESPONSE']._serialized_start=220
  _globals['_GETVALUERESPONSE']._serialized_end=261
  _globals['_STOREVALUEREQUEST']._serialized_start=263
  _globals['_STOREVALUEREQUEST']._serialized_end=318
  _globals['_KEYVALUESERVICE']._serialized_start=320
  _globals['_KEYVALUESERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
